import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import {
  getDatabase,
  ref,
  query,
  onValue,
  limitToLast,
} from "firebase/database";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

const firebaseConfig = {
  apiKey: "AIzaSyBkhAublGaFV2yjuY1M0nfx3QA4bTFXCWs",
  authDomain: "aistfypgp0.firebaseapp.com",
  databaseURL: "https://aistfypgp0-default-rtdb.firebaseio.com",
  projectId: "aistfypgp0",
  storageBucket: "aistfypgp0.appspot.com",
  messagingSenderId: "911309123203",
  appId: "1:911309123203:web:26c88ea0d94debcb7c35b6",
  measurementId: "G-YQEJXNNM8M",
};

const app = initializeApp(firebaseConfig);
const db = getDatabase(app);

export default function Home() {
  const [hum, setHum] = useState(0);
  const [temp, setTemp] = useState(0);
  const [time, setTime] = useState("N/A")
  
  useEffect(() => {
    const dataRef = query(ref(db, "ESP32_APP/"), limitToLast(1));
    onValue(dataRef, (snapshot) => {
      const data = snapshot.val();

      for(var value in data){
        setHum(data[value].humidity);
        setTemp(data[value].temperature);
        setTime(data[value].timestamp);
      }
    });
  }, []);

  return (
    <>
      <Head>
        <title>Smart Plant Pot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Final Year Project</p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            ></a>
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>Humidity</h2>
            <p className={inter.className}>{hum}</p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Temperature
            </h2>
            <p className={inter.className}>
              {temp}
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Timestamp
            </h2>
            <p className={inter.className}>
              {time}
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
